version: '3'
services:

  node1:
    image: cassandra:4.0
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
      CASSANDRA_CLUSTER_NAME: demo
      CASSANDRA_SEEDS: node1
    volumes:
      - ./files:/files
    restart: unless-stopped

#  node2:
#    image: cassandra:4.0
#    environment:
#      CASSANDRA_CLUSTER_NAME: demo
#      CASSANDRA_SEEDS: node1,node2
#    restart: unless-stopped
  kafka-ui:
    container_name: kafka-ui
    image: consdata/kouncil:latest
    ports:
      - 8083:8080
    environment:
        - bootstrapServers=kafka:9094
        - kouncil.auth.active-provider=inmemory
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "kafka:/bitnami"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL://kafka:9094
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - BITNAMI_DEBUG=yes
      - KAFKA_CFG_NUM_PARTITIONS=2
  worker1:
    image: worker
    build:
        context: ./worker
        dockerfile: app.Dockerfile
    environment:
        - KAFKA_BROKER=kafka:9094
        - WORKER_ID=0
        - WORKER_COUNT=3
        - KAFKA_JOBS_GROUP=jobs
        - PARTITIONS_COUNT=12
    ports:
      - "8884:8884"
    expose:
      - "8884"
  worker2:
    image: worker
    build:
      context: ./worker
      dockerfile: app.Dockerfile
    environment:
      - KAFKA_BROKER=kafka:9094
      - WORKER_ID=1
      - WORKER_COUNT=3
      - KAFKA_JOBS_GROUP=jobs
      - PARTITIONS_COUNT=12
    ports:
      - "8885:8884"
    expose:
      - "8885"
  worker3:
    image: worker
    build:
      context: ./worker
      dockerfile: app.Dockerfile
    environment:
      - KAFKA_BROKER=kafka:9094
      - WORKER_ID=2
      - WORKER_COUNT=3
      - KAFKA_JOBS_GROUP=jobs
      - PARTITIONS_COUNT=12
    ports:
      - "8886:8884"
    expose:
      - "8886"
  job-orchestrator:
    image: job-orchestrator
    build:
      context: ./job-orchestrator
      dockerfile: app.Dockerfile
    environment:
      - KAFKA_BROKER=kafka:9094
      - WORKER_COUNT=3
      - PARTITIONS_COUNT=12
      - WORKER_URLS=http://worker1:8884/health,http://worker2:8884/health,http://worker3:8884/health
      - DB_URL=node1
volumes:
    kafka:
        driver: local